### ISSUE TITLE
API services down

### ISSUE THREAD

**Issue by melvincwng** [skolakoda/programming-quotes-api#56] opened 2023-01-02 10:51 UTC
Seems like all the API endpoints are not available at this time of writing (refer screenshot below):

![image](https://user-images.githubusercontent.com/77479885/210221468-0859796f-820c-4d25-a0f6-4a36e1d5ebca.png)

I understand it could be due to [the removal of Heroku Free plans](https://help.heroku.com/RSBRUH58/removal-of-heroku-free-product-plans-faq), hence leading to the server endpoints not working at the moment.

Are there any plans by the dev team to switch to hosting on another platform instead? 

Platforms like **Render/Railway/Cyclic.sh** do offer free hosting services (if I recall correctly) and are relatively easy to deploy into.

Hope to receive updates/clarifications by the dev team regarding this, thanks 😄

**Comment by mudroljub** [comment] 2023-08-01 10:51
duplicate of #54

**Closed by mudroljub** 2023-08-01 10:51 UTC
